### ISSUE TITLE
Hook up main menu button functionalities 

### ISSUE THREAD

**Issue by hichd** [LHuss/capstone#26]
## Purpose
Hook up new and open buttons to their intended functionalities. 
![Untitled Diagram (4)](https://user-images.githubusercontent.com/35614850/69492061-2566b900-0e6b-11ea-9025-a62eae9d3edb.png)
![Untitled Diagram (8)](https://user-images.githubusercontent.com/35614850/71604670-9b78d280-2b31-11ea-9eb2-bd82c7665862.png)

## Context
The new button will open up a new scene with a sphere in the center. 
The open button will allow the user to import existing files.
Importing a new object will attach the script to the object and scale it to the window.
## ToDo
- [x] make a mock up
- [x] refactor main menu to controller architecture
- [x] new button opens scene with sphere
- [x] apply mesh deformation to object in newly opened scene
- [x] open button opens import scene
- [x] loading screen between scenes
- [x] testing
